---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    name: Development CI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: echo "node_version=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
        id: cat-nvmrc

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.cat-nvmrc.outputs.node_version}}

      - run: npm run build-dist

      - name: Check if build left artifacts
        run: git diff --exit-code

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.3'

      - run: npm run test

  action:
    name: Action CI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.3'

      - name: Use paulo-ferraz-oliveira/setup-elp
        id: setup-elp
        uses: ./
        with:
          elp-version: '2024-06-07'

      - run: elp version
